# Generated by Django 2.0.2 on 2018-12-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('osrah', models.IntegerField(db_column='Osrah', primary_key=True, serialize=False)),
                ('pib', models.CharField(db_column='PIB', max_length=70)),
                ('adress', models.CharField(db_column='Adress', max_length=70)),
                ('meter', models.IntegerField(db_column='Meter')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Abonent_comercial',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('edrpoy', models.FloatField(db_column='EDRPOY', max_length=9, primary_key=True, serialize=False)),
                ('adress', models.CharField(db_column='Adress', max_length=70)),
                ('contrNum', models.FloatField(db_column='ContractNum', max_length=20, primary_key=True)),
                ('taxNum', models.FloatField(db_column='TaxNum', max_length=20, primary_key=True)),
                ('certificateNum', models.FloatField(db_column='CerttificateNum', max_length=32, primary_key=True)),
                ('phoneNum', models.FloatField(db_column='PhoneNum', max_length=20)),
                ('date', models.DateField(db_column='DateContract', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Oplata',
            fields=[
                ('idoplata', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('saldo', models.FloatField()),
                ('annotation', models.CharField(default=0, max_length=45)),
                ('dateOpl', models.CharField(default=None, max_length=45)),
                ('abonent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonent.Abonent')),
            ],
        ),
        migrations.CreateModel(
            name='Rahunok',
            fields=[
                ('idrahunok', models.AutoField(db_column='idRahunok', primary_key=True, serialize=False)),
                ('datarah', models.DateField()),
                ('pokaz1', models.FloatField()),
                ('pokaz2', models.FloatField()),
                ('spozkwt', models.FloatField(db_column='SpozKWT')),
                ('spozuah', models.FloatField(db_column='SpozUAH')),
                ('abonent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonent.Abonent')),
            ],
        ),
    ]
