# Generated by Django 2.0.2 on 2018-05-04 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('osrah', models.IntegerField(db_column='Osrah', primary_key=True, serialize=False)),
                ('pib', models.CharField(db_column='PIB', max_length=70)),
                ('adress', models.CharField(db_column='Adress', max_length=70)),
                ('meter', models.IntegerField(db_column='Meter')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oplata',
            fields=[
                ('idoplata', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('saldo', models.FloatField()),
                ('idstala', models.IntegerField(db_column='idStala')),
                ('annotation', models.CharField(default=0, max_length=45)),
                ('dateOpl', models.DateField(default=0)),
                ('abonent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonent.Abonent')),
            ],
        ),
        migrations.CreateModel(
            name='Rahunok',
            fields=[
                ('idrahunok', models.AutoField(db_column='idRahunok', primary_key=True, serialize=False)),
                ('idstala', models.IntegerField(db_column='idStala')),
                ('datarah', models.DateField(db_column='dataRah')),
                ('pokaz1', models.FloatField()),
                ('pokaz2', models.FloatField()),
                ('spozkwt', models.FloatField(db_column='SpozKWT')),
                ('spozuah', models.FloatField(db_column='SpozUAH')),
                ('abonent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonent.Abonent')),
            ],
        ),
    ]
