# Generated by Django 2.0.2 on 2018-05-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplata',
            name='dateOpl',
            field=models.CharField(default=0, max_length=45),
        ),
    ]
