# Generated by Django 2.0.2 on 2018-05-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonent', '0003_remove_oplata_idstala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rahunok',
            name='idstala',
        ),
    ]
