# Generated by Django 2.0.2 on 2018-12-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget_HW',
            fields=[
                ('id_HW', models.IntegerField(db_column='idGadget', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='PIB', max_length=70)),
                ('adress', models.CharField(db_column='Adress', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kWh', models.FloatField(blank=True, db_column='kWh', null=True)),
                ('kvarh_p', models.FloatField(blank=True, db_column='kVArh_p', null=True)),
                ('kvarh_n', models.FloatField(blank=True, db_column='kVArh_n', null=True)),
                ('kvah', models.FloatField(blank=True, db_column='kVAh', null=True)),
                ('cur_sum_v', models.FloatField(blank=True, db_column='cur_sum_V', null=True)),
                ('cur_l1_v', models.FloatField(blank=True, db_column='cur_L1_V', null=True)),
                ('cur_l2_v', models.FloatField(blank=True, db_column='cur_L2_V', null=True)),
                ('cur_l3_v', models.FloatField(blank=True, db_column='cur_L3_V', null=True)),
                ('cur_f', models.FloatField(blank=True, db_column='cur_F', null=True)),
                ('meterDate', models.BigIntegerField(db_column='meterDate')),
                ('gadget_HW', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gadget_HW.Gadget_HW')),
            ],
        ),
        migrations.CreateModel(
            name='Meter_max_dem_h',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kW', models.FloatField(blank=True, db_column='kW', null=True)),
                ('meterDate', models.DateField()),
                ('gadget_HW', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gadget_HW.Gadget_HW')),
            ],
        ),
    ]
